#!/usr/bin/env bash

# $@ contains the 'subject' of the notification, along the lines of:
#    'Restic - example-job backup-full OK'
# The body of the mail will be read from stdin

SCRIPT=`realpath $0`
SCRIPTPATH=`dirname $SCRIPT`

source $SCRIPTPATH/configs/smtp.env

s-nail -s "$@" \
    -S v15-compat \
    -S smtp-use-starttls \
    -S smtp-auth=login \
    -S mta=smtp://${NOTIFICATION_SMTP_USER}:${NOTIFICATION_SMTP_PASSWORD}@${NOTIFICATION_SMTP_URL} \
    -S from="$NOTIFICATION_MAIL_FROM" \
    $NOTIFICATION_MAIL_TO

